# Site
encoding: UTF-8
title: 幹話聊軟體
description: 一日不幹話，便覺面目可憎
theme: jekyll-theme-hacker
avatar: https://avatars2.githubusercontent.com/u/55027266

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
