# Site
encoding: UTF-8
title: 幹話講軟體
description: 幹話講軟體
theme: jekyll-theme-hacker

# Authors
authors:
  miles:
    name: Miles Chou
    display_name: Miles
    gravatar: bad2e80b8b7e4c97d759bcd12377aece
    email: jangconan@gmail.com
    github: MilesChou
